name: Test and Release
concurrency:
  group: mainline
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"

jobs:
  check-types:
    name: Check Types
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Configure node 18
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"

      - name: Install Dependencies
        run: yarn install
      - name: Run tsc
        run: yarn check-types

  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Configure node 18
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"

      - name: Install Dependencies
        run: yarn install
      - name: Run Tests
        run: yarn test

  run-linting:
    name: Run Linting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Configure node 18
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"

      - name: Install Dependencies
        run: yarn install
      - name: Run Tests
        run: yarn lint

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [check-types, run-linting, run-tests]

    steps:
      - uses: actions/checkout@v3
      - name: Configure node 18
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"

      - name: Install Dependencies
        run: yarn install

      - name: Build Package
        run: yarn build

      - name: Release
        uses: cycjimmy/semantic-release-action@v3.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
